--- a/.github/workflows/TEST.yml
+++ b/.github/workflows/TEST.yml
@@ -67,4 +67,4 @@
       - { name: e2e multi test and hotreload, if: "${{ matrix.e2e }}", working-directory: e2e/e2e-test-multi, run: "./gradlew --watch-fs --warn --configuration-cache --configuration-cache-problems=warn compileKotlinJvm" }
       - { name: e2e multi test runJvmAutoreload, if: "${{ matrix.e2e }}", working-directory: e2e/e2e-test-multi, run: "./gradlew --configuration-cache :client:runJvmAutoreload" }
       - { name: e2e multi test packageJvmFatJar, if: "${{ matrix.e2e }}", working-directory: e2e/e2e-test-multi, run: "./gradlew --configuration-cache :client:packageJvmFatJar" }
-      - { name: Check publication includes iOS, if: "${{ matrix.e2e }}", run: ./gradlew checkModulePublication }
+      - { name: Check publication includes iOS, if: "${{ matrix.e2e }}", run: ./gradlew checkModulePublication }